baseURL: 'https://ny1030.github.io/pages'
canonifyurl: 'true'

title: ny1030.github.io
paginate: 5
theme: PaperMod
defaultContentLanguage: ja

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    minifyOutput: true

googleAnalytics: "G-4LRDXP31GR"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
    title: ny1030.github.io
    description: "ny1030's portal site"
    keywords: [ny1030, portal, Blog, Portfolio, engineering]
    author: Y Nakajima
    DateFormat: "January 2, 2006"
    defaultTheme: auto
    disableThemeToggle: false

    homeInfoParams:
        Title: "WelcomeðŸ™Œ"
        Content: "I am into software engineering, gadget, food, sleep"

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: true
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    socialIcons:
        - name: twitter
          url: "https://twitter.com/"
        - name: github
          url: "https://github.com/ny1030"
        - name: linkedin
          url: "https://www.linkedin.com/in/"

menu:
    main:
    - identifier: search
      name: ðŸ”Ž search
      url: /search
      weight: 10
    - identifier: archive
      name: ðŸ“š archive
      url: /archives
      weight: 20

